#!/bin/bash

# Install native dependencies
apt update
apt install -y python3 python3-pip

# Fix certificate authorities on armv7
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

# Make release
if [ "$1" = 'binary' ]; then
    # Install native development dependencies
    apt install -y make build-essential python3-dev patchelf zlib1g-dev upx scons

    # Install dependencies
    make depend

    make release
else
    # Install dependencies
    pip3 install -r requirements.txt
fi
