import os

from consumatio.app import App
from consumatio.constants import DEFAULT_DATABASE_URI
from consumatio.external.db.models import *
from consumatio.usecases.get_by_rating import get_by_rating
from tests.tmdb.tmdb_mock import TmdbMock


def test_get_by_rating_movie():
    tmdb_key = os.getenv("TMDB_KEY")
    app = App(
        tmdb_key, "mysecret",
        DEFAULT_DATABASE_URI,
        None, False)
    app.configure()

    app.app.app_context().push()
    tmdb = TmdbMock(tmdb_key, db)

    dict = {
        'total_pages':
        5,
        'results': [{
            'code': 337404,
            'title': 'Cruella',
            'genres': None,
            'overview':
            'In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.',
            'popularity': 6821.402,
            'rating_average': 8.8,
            'rating_count': 1560,
            'release_date': '2021-05-27',
            'runtime': None,
            'status': None,
            'backdrop_path': '/6MKr3KgOLmzOP6MSuZERO41Lpkt.jpg',
            'poster_path': '/A0knvX7rlwTyZSKj8H5NiARb45.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/337404',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 663558,
            'title': 'New Gods: Nezha Reborn',
            'genres': None,
            'overview':
            '3000 years after the boy-god Nezha conquers the Dragon King then disappears in mythological times, he returns as an ordinary man to find his own path to becoming a true hero.',
            'popularity': 408.949,
            'rating_average': 8.6,
            'rating_count': 169,
            'release_date': '2021-04-12',
            'runtime': None,
            'status': None,
            'backdrop_path': '/y0SiXoTLQp93NbLQ4XhgVz18UAS.jpg',
            'poster_path': '/6goDkAD6J3br81YMQf0Gat8Bqjy.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/663558',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 791373,
            'title': "Zack Snyder's Justice League",
            'genres': None,
            'overview':
            "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
            'popularity': 907.096,
            'rating_average': 8.5,
            'rating_count': 5661,
            'release_date': '2021-03-18',
            'runtime': None,
            'status': None,
            'backdrop_path': '/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg',
            'poster_path': '/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/791373',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 615457,
            'title': 'Nobody',
            'genres': None,
            'overview':
            'Hutch Mansell, a suburban dad, overlooked husband, nothing neighbor — a "nobody." When two thieves break into his home one night, Hutch\'s unknown long-simmering rage is ignited and propels him on a brutal path that will uncover dark secrets he fought to leave behind.',
            'popularity': 1048.459,
            'rating_average': 8.5,
            'rating_count': 1804,
            'release_date': '2021-06-10',
            'runtime': None,
            'status': None,
            'backdrop_path': '/6zbKgwgaaCyyBXE4Sun4oWQfQmi.jpg',
            'poster_path': '/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/615457',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 423108,
            'title': 'The Conjuring: The Devil Made Me Do It',
            'genres': None,
            'overview':
            "Paranormal investigators Ed and Lorraine Warren encounter what would become one of the most sensational cases from their files. The fight for the soul of a young boy takes them beyond anything they'd ever seen before, to mark the first time in U.S. history that a murder suspect would claim demonic possession as a defense.",
            'popularity': 300.334,
            'rating_average': 7.8,
            'rating_count': 34,
            'release_date': '2021-07-01',
            'runtime': None,
            'status': None,
            'backdrop_path': '/gr2bdQ12cK4VA7EaIgtmDcbdALP.jpg',
            'poster_path': '/isghxwTkgHsSfoEmXK1QZEYTjUl.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/423108',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 385128,
            'title': 'F9',
            'genres': None,
            'overview':
            'Dom Toretto is leading a quiet life off the grid with Letty and his son, little Brian, but little do they know, is that danger always lurks just over their peaceful horizon. This time, that threat will force Dom to confront the sins of his past if he’s going to save those he loves most. His crew joins together to stop a world-shattering plot led by the most skilled assassin and high-performance driver they’ve ever encountered: a man who also happens to be Dom’s forsaken brother, Jakob.',
            'popularity': 489.72,
            'rating_average': 8.3,
            'rating_count': 82,
            'release_date': '2021-07-08',
            'runtime': None,
            'status': None,
            'backdrop_path': '/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg',
            'poster_path': '/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/385128',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 785534,
            'title': 'Paper Lives',
            'genres': None,
            'overview':
            'In the streets of Istanbul, ailing waste warehouse worker Mehmet takes a small boy under his wing and must soon confront his own traumatic childhood.',
            'popularity': 75.203,
            'rating_average': 8.3,
            'rating_count': 216,
            'release_date': '2021-03-12',
            'runtime': None,
            'status': None,
            'backdrop_path': '/ctckqAvz9aTZDtfXLmDUdMflesU.jpg',
            'poster_path': '/cmru6N6Hnw2pJwuo1ctH1CxKqKZ.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/785534',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 527774,
            'title': 'Raya and the Last Dragon',
            'genres': None,
            'overview':
            'Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. But when an evil force threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, that same evil has returned and it’s up to a lone warrior, Raya, to track down the legendary last dragon to restore the fractured land and its divided people.',
            'popularity': 1055.191,
            'rating_average': 8.2,
            'rating_count': 3001,
            'release_date': '2021-03-05',
            'runtime': None,
            'status': None,
            'backdrop_path': '/hJuDvwzS0SPlsE6MNFOpznQltDZ.jpg',
            'poster_path': '/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/527774',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 399566,
            'title': 'Godzilla vs. Kong',
            'genres': None,
            'overview':
            'In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.',
            'popularity': 1399.418,
            'rating_average': 8.1,
            'rating_count': 5808,
            'release_date': '2021-03-25',
            'runtime': None,
            'status': None,
            'backdrop_path': '/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg',
            'poster_path': '/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/399566',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 458220,
            'title': 'Palmer',
            'genres': None,
            'overview':
            "After 12 years in prison, former high school football star Eddie Palmer returns home to put his life back together—and forms an unlikely bond with Sam, an outcast boy from a troubled home. But Eddie's past threatens to ruin his new life and family.",
            'popularity': 61.618,
            'rating_average': 8,
            'rating_count': 473,
            'release_date': '2021-01-29',
            'runtime': None,
            'status': None,
            'backdrop_path': '/bblKpucB0XbyQBmfXsaRN985Rgh.jpg',
            'poster_path': '/xSDdRAjxKAGi8fUBLOqSrBhJmF0.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/458220',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 501929,
            'title': 'The Mitchells vs. the Machines',
            'genres': None,
            'overview':
            "A quirky, dysfunctional family's road trip is upended when they find themselves in the middle of the robot apocalypse and suddenly become humanity's unlikeliest last hope.",
            'popularity': 121.52,
            'rating_average': 8,
            'rating_count': 859,
            'release_date': '2021-04-30',
            'runtime': None,
            'status': None,
            'backdrop_path': '/qXMXmhsJeW28DYp5iOar9BGepVS.jpg',
            'poster_path': '/mI2Di7HmskQQ34kz0iau6J1vr70.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/501929',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 637649,
            'title': 'Wrath of Man',
            'genres': None,
            'overview':
            "A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.",
            'popularity': 3381.321,
            'rating_average': 8,
            'rating_count': 606,
            'release_date': '2021-05-20',
            'runtime': None,
            'status': None,
            'backdrop_path': '/77tui163estZrQ78NBggqDB4n2C.jpg',
            'poster_path': '/YxopfHpsCV1oF8CZaL4M3Eodqa.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/637649',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 736069,
            'title': 'Justice Society: World War II',
            'genres': None,
            'overview':
            'While speeding off to help in an impromptu battle, The Flash blazes and rips through time, only to find himself dropped into the middle of World War II. It’s here that The Flash meets Wonder Woman and her top secret team, known as the Justice Society of America. Amidst the raging tides of war, gripping combat and the velocity of valor, The Flash must fight to return to his own timeline.',
            'popularity': 372.224,
            'rating_average': 7.9,
            'rating_count': 218,
            'release_date': '2021-04-27',
            'runtime': None,
            'status': None,
            'backdrop_path': '/8LHSDyRizQ4kQz5rEHPKyXPvMG3.jpg',
            'poster_path': '/e4REOC6CZW8J6FslA4nRvdQXFXR.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/736069',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 726684,
            'title': 'Miraculous World: Shanghai – The Legend of Ladydragon',
            'genres': None,
            'overview':
            'On school break, Marinette heads to Shanghai to meet Adrien. But after arriving, Marinette loses all her stuff, including the Miraculous that allows her to turn into Ladybug!',
            'popularity': 964.043,
            'rating_average': 7.9,
            'rating_count': 375,
            'release_date': '2021-05-23',
            'runtime': None,
            'status': None,
            'backdrop_path': '/rlNnwObbMu5G2FaOUlacnUIdIIA.jpg',
            'poster_path': '/msI5a9TPnepx47JUb2vl88hb80R.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/726684',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 586047,
            'title': 'Seobok',
            'genres': None,
            'overview':
            'A former intelligence agent gets involved with the first human clone, Seo Bok, who others seek, causing trouble.',
            'popularity': 745.953,
            'rating_average': 7.7,
            'rating_count': 54,
            'release_date': '2021-07-23',
            'runtime': None,
            'status': None,
            'backdrop_path': '/yC4DRg5aGgNpkHpUDpLtBqzownS.jpg',
            'poster_path': '/nxxuWC32Y6TULj4VnVwMPUFLIpK.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/586047',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 809236,
            'title': 'Have You Ever Seen Fireflies?',
            'genres': None,
            'overview':
            'Rebellious, irreverent wunderkind Gülseren navigates loneliness, love and loss against the current of political turmoil and social change.',
            'popularity': 2.908,
            'rating_average': 7.6,
            'rating_count': 15,
            'release_date': '2021-04-09',
            'runtime': None,
            'status': None,
            'backdrop_path': '/lVhSW3OcQ6Z6M4f4yMhrlHgPzc1.jpg',
            'poster_path': '/lZucbxHPkb5Xla5ivOcKim7A1NO.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/809236',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 460465,
            'title': 'Mortal Kombat',
            'genres': None,
            'overview':
            "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
            'popularity': 1641.256,
            'rating_average': 7.6,
            'rating_count': 2837,
            'release_date': '2021-05-06',
            'runtime': None,
            'status': None,
            'backdrop_path': '/mPBI506o7gITnjoSkcyPneK9s8n.jpg',
            'poster_path': '/nkayOAUBUu4mMvyNf9iHSUiPjF1.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/460465',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 773736,
            'title': 'TINA',
            'genres': None,
            'overview':
            'Tina Turner overcame impossible odds to become one of the first female African American artists to reach a mainstream international audience. Her road to superstardom is an undeniable story of triumph over adversity. It’s the ultimate story of survival – and an inspirational story of our times.',
            'popularity': 15.184,
            'rating_average': 7.6,
            'rating_count': 26,
            'release_date': '2021-03-02',
            'runtime': None,
            'status': None,
            'backdrop_path': '/rv3bNtqYpARfJNPFctMeZrxq6bL.jpg',
            'poster_path': '/bL2FNPhiPqDyirzU3rfaXDiWRXs.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/773736',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 583689,
            'title': 'Moxie',
            'genres': None,
            'overview':
            "Inspired by her mom's rebellious past and a confident new friend, a shy 16-year-old publishes an anonymous zine calling out sexism at her school.",
            'popularity': 74.43,
            'rating_average': 7.5,
            'rating_count': 463,
            'release_date': '2021-03-03',
            'runtime': None,
            'status': None,
            'backdrop_path': '/aKIrKbszS7Kq0aTGTCRTYMp1EDX.jpg',
            'poster_path': '/aLBo1Ca9PggcWY98ItW5ZkdxTuA.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/583689',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }, {
            'code': 785976,
            'title': 'Pelé',
            'genres': None,
            'overview':
            "Against the backdrop of a turbulent era in Brazil, this documentary captures Pelé's extraordinary path from breakthrough talent to national hero. Mixing rare archival footage and exclusive interviews, this documentary celebrates the legendary Brazilian footballer who personified football as art.",
            'popularity': 30.496,
            'rating_average': 7.5,
            'rating_count': 89,
            'release_date': '2021-02-23',
            'runtime': None,
            'status': None,
            'backdrop_path': '/t0kHIE4ERtw3h4qwTSmzt5LyhRY.jpg',
            'poster_path': '/tX2gco2U4MlKEWwM4UkiIf1C74e.jpg',
            'providers': None,
            'cast': None,
            'directors': None,
            'tmdb_url': 'https://www.themoviedb.org/movie/785976',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            '__typename': 'Movie'
        }]
    }

    assert dict == get_by_rating("e3b0c4429@e3b0c4429.com", tmdb, "Movie", 5,
                                 10, "2021-01-01", 1)


def test_get_by_rating_tv():
    tmdb_key = os.getenv("TMDB_KEY")
    app = App(
        tmdb_key, "mysecret",
        DEFAULT_DATABASE_URI,
        None, False)
    app.configure()

    app.app.app_context().push()
    tmdb = TmdbMock(tmdb_key, db)

    dict = {
        'total_pages':
        7,
        'results': [{
            'code': 115194,
            'title': 'A Perfect Planet',
            'genres': None,
            'overview':
            'A unique fusion of blue chip natural history and earth science that explains how our living planet operates. This five-part series shows how the forces of nature drive, shape and support Earth’s great diversity of wildlife.',
            'popularity': 35.725,
            'rating_average': 9.5,
            'rating_count': 14,
            'first_air_date': '2021-01-03',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/59amxr7vKdeaWfv09y8UG8yZ6v.jpg',
            'poster_path': '/8JJa4gduVytwpXQzFtZNibRA6S.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/115194',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 114547,
            'title': 'Secrets of Sulphur Springs',
            'genres': None,
            'overview':
            '12-year-old Griffin Campbell and his family move to the small town of Sulphur Springs and take ownership of an abandoned hotel rumored to be haunted by the ghost of a girl who disappeared decades ago. Griffin befriends Harper, a bright-eyed, mystery-obsessed classmate and together, they uncover a secret portal that allows them to travel back in time. In the past, they’ll attempt to uncover the key to solving this unsolved mystery, a mystery that affects everyone close to them.',
            'popularity': 10.137,
            'rating_average': 9.1,
            'rating_count': 17,
            'first_air_date': '2021-01-15',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/5zTeE4HqzzhN3w6FgyfVMPgtkqc.jpg',
            'poster_path': '/30MqitTOgIfeOhvwdMHkrM9p5mD.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/114547',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 110309,
            'title': 'SK8 the Infinity',
            'genres': None,
            'overview':
            '"S" is a dangerous, top secret, no-holds-barred downhill skateboarding race down an abandoned mine. When avid skateboarder Reki takes Langa to the mountain where "S" is held, Langa, who’s never been on a skateboard in his life, finds himself sucked into the world of "S" and...?!',
            'popularity': 57.449,
            'rating_average': 9.2,
            'rating_count': 10,
            'first_air_date': '2021-01-10',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/ohOrfdh80HVY5QBD8kV2FYYSVwF.jpg',
            'poster_path': '/ksb6QlSCsRLr3MNmxc8ojOOLK6V.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/110309',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 116386,
            'title': 'Doom at Your Service',
            'genres': None,
            'overview':
            'Dong-kyung has been working hard ever since her parents passed away. Her life seems to get stable after working as an web novel editor for 6 years, but one day she gets diagnosed with a brain cancer. She blames her unlucky life and wishes to curse everything to disappear, which unintentionally calls Myul Mang, a messenger between humans and gods, to appear. He says that he can grant her wishes. As her last hope, she makes a contract with Myul Mang for hundred days to live as how she wants, risking her everything.',
            'popularity': 19.571,
            'rating_average': 9,
            'rating_count': 11,
            'first_air_date': '2021-05-10',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/uMLihaxfbeCvraDmER37t2jTNKi.jpg',
            'poster_path': '/tgsWD4dJI5YFY8Kyk6vVjZoIKfO.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/116386',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 121509,
            'title': 'The Upshaws',
            'genres': None,
            'overview':
            'Bennie Upshaw, the head of a Black working class family in Indianapolis, is a charming, well-intentioned mechanic and lifelong mess just trying his best to step up and care for his family and tolerate his sardonic sister-in-law, all without a blueprint for success.',
            'popularity': 5.407,
            'rating_average': 8.9,
            'rating_count': 10,
            'first_air_date': '2021-05-12',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/2etWIt4JMD4wHzJIZVi7YeI5UZa.jpg',
            'poster_path': '/bgtpwAsKNfqJmgp3zBxuSHMBAaW.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/121509',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 95557,
            'title': 'Invincible',
            'genres': None,
            'overview':
            'Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father’s tutelage.',
            'popularity': 599.292,
            'rating_average': 8.9,
            'rating_count': 1934,
            'first_air_date': '2021-03-26',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/6UH52Fmau8RPsMAbQbjwN3wJSCj.jpg',
            'poster_path': '/yDWJYRAwMNKbIYT8ZB33qy84uzO.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/95557',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 99071,
            'title': 'Redo of Healer',
            'genres': None,
            'overview':
            'In a world of monsters, adventurers and magic, some of the most gifted healers are subjugated to brute force. Keyaru gains the ability to rewind time and turns the tables on those who’ve exploited him in this dark fantasy tale of vengeance and fury.',
            'popularity': 65.563,
            'rating_average': 8.8,
            'rating_count': 363,
            'first_air_date': '2021-01-13',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/e30T3teKp6VZlIXhI0AhTDksvoy.jpg',
            'poster_path': '/hynFI7MltF1BBvroh3iJplnBZyc.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/99071',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 117376,
            'title': 'Vincenzo',
            'genres': None,
            'overview':
            'Vincenzo Cassano is an Italian lawyer and Mafia consigliere who moves back to Korea due to a conflict within his organization. He ends up crossing paths with a sharp-tongued lawyer named Cha-young, and the two join forces in using villainous methods to take down villains who cannot be punished by the law.',
            'popularity': 98.999,
            'rating_average': 8.8,
            'rating_count': 169,
            'first_air_date': '2021-02-20',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/sf7NCqyVUNoyjYuwW5oJke1T1lH.jpg',
            'poster_path': '/dvXJgEDQXhL9Ouot2WkBHpQiHGd.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/117376',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 116249,
            'title': 'Kid Cosmic',
            'genres': None,
            'overview':
            "A boy's superhero dreams come true when he finds five powerful cosmic stones. But saving the day is harder than he imagined — and he can't do it alone.",
            'popularity': 21.83,
            'rating_average': 8.8,
            'rating_count': 33,
            'first_air_date': '2021-02-02',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/3twr9PEWUxb6FHVZ8hzOaBpSh8u.jpg',
            'poster_path': '/88HdcCMumGqGAt2kR3vVOr8NYiA.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/116249',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 95205,
            'title': 'The Equalizer',
            'genres': None,
            'overview':
            'Robyn McCall, an enigmatic former CIA operative with a mysterious background, uses her extensive skills to help those with nowhere else to turn.',
            'popularity': 11.024,
            'rating_average': 8.7,
            'rating_count': 57,
            'first_air_date': '2021-02-07',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/3C032MHjf4sXV3XpmvRLbsibAmZ.jpg',
            'poster_path': '/gAgShytJMWSYkjxa7ZDjSZhsnlc.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/95205',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 105971,
            'title': 'The Bad Batch',
            'genres': None,
            'overview':
            'Follow the elite and experimental Clones of the Bad Batch as they find their way in a rapidly changing galaxy in the aftermath of the Clone Wars.',
            'popularity': 386.457,
            'rating_average': 8.7,
            'rating_count': 246,
            'first_air_date': '2021-05-04',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/sjxtIUCWR74yPPcZFfTsToepfWm.jpg',
            'poster_path': '/WjQmEWFrOf98nT5aEfUfVYz9N2.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/105971',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 110070,
            'title': 'Horimiya',
            'genres': None,
            'overview':
            'A secret life is the one thing they have in common. At school, Hori is a prim and perfect social butterfly, but the truth is she’s a brash homebody. Meanwhile, under a gloomy facade, Miyamura hides a gentle heart, along with piercings and tattoos. In a chance meeting, they both reveal a side they’ve never shown. Could this blossom into something new?',
            'popularity': 102.268,
            'rating_average': 8.7,
            'rating_count': 204,
            'first_air_date': '2021-01-10',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/4u64tHtUkna1y4OkJcrXLEhhLLy.jpg',
            'poster_path': '/917VL7zHTaltnEBDrKWVITTsvLy.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/110070',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 105009,
            'title': 'Tokyo Revengers',
            'genres': None,
            'overview':
            'Takemichi Hanagaki is a freelancer that’s reached the absolute pits of despair in his life. He finds out that the only girlfriend he ever had, in middle school, Hinata Tachibana, had been killed by the ruthless Tokyo Manji Gang. The day after hearing about her death, he’s standing on the station platform and ends up being pushed over onto the tracks by a herd of people. He closes his eyes thinking he’s about to die, but when he opens his eyes back up, he somehow had gone back in time 12 years. Now that he’s back living the best days of his life, Takemichi decides to get revenge on his life.',
            'popularity': 156.682,
            'rating_average': 8.7,
            'rating_count': 11,
            'first_air_date': '2021-04-11',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/wjw3wrmkjjApu83Y4SxmQ5gP2mZ.jpg',
            'poster_path': '/qSEKyf0fWhrCEQ3LTwLqe41eSvR.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/105009',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 112160,
            'title': 'The Way of the Househusband',
            'genres': None,
            'overview':
            'Tatsu, a notorious and feared yakuza leader nicknamed "The Immortal Dragon," withdraws from the criminal syndicate and becomes a housekeeper to help his wife, Miku. The series features a variety of comedic settings, typically showing Tatsu\'s domestic activities and intimidating inequality with his looks, as well as multiple encounters with his former colleagues and rivals in the Japanese Criminal Syndicate.',
            'popularity': 18.938,
            'rating_average': 8.6,
            'rating_count': 129,
            'first_air_date': '2021-04-08',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/3bC5QIJ3P1ebC7PKwzUVfgub8I.jpg',
            'poster_path': '/p63rAZt0s8kedJtdxGwD5VYZafc.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/112160',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 106158,
            'title': 'Law & Order: Organized Crime',
            'genres': None,
            'overview':
            'Detective Elliot Stabler returns to the NYPD to battle organized crime after a devastating personal loss. The city and police department have changed dramatically in the decade he’s been away, and he must adapt to a criminal justice system in the midst of its own moment of reckoning. Stabler journeys to find absolution and rebuild his life, while leading a new elite task force that is taking apart the city’s most powerful criminal syndicates one by one.',
            'popularity': 14.692,
            'rating_average': 8.6,
            'rating_count': 15,
            'first_air_date': '2021-04-01',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/tjogqNxMYdXb7UMr4DofAAUdzyb.jpg',
            'poster_path': '/ur8ZV6Dn4FzsU2zIQK7iDQKZcTE.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/106158',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 120462,
            'title': 'THEM',
            'genres': None,
            'overview':
            'A limited anthology series that explores terror in America.',
            'popularity': 12.714,
            'rating_average': 8.5,
            'rating_count': 35,
            'first_air_date': '2021-04-09',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/nRifrfdncHTRKUbk0MrAcuQmDFN.jpg',
            'poster_path': '/bJw1VZ4ACt5TnAvJbHcprzgYc1E.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/120462',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 112162,
            'title': 'Pacific Rim: The Black',
            'genres': None,
            'overview':
            'Two siblings - an idealistic teenage boy and his naïve younger sister - are forced to pilot an abandoned Jaeger across a hostile landscape in a desperate attempt to find their missing parents.',
            'popularity': 44.881,
            'rating_average': 8.5,
            'rating_count': 193,
            'first_air_date': '2021-03-04',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/o56X5GUWgzkGJ90QDWn6NNkGEN7.jpg',
            'poster_path': '/s3mOpPwrcKCPVkSWGqEwOah4jdX.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/112162',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 112163,
            'title': 'High-Rise Invasion',
            'genres': None,
            'overview':
            "High-school girl Yuri suddenly finds herself on the rooftop of a high-rise building. She's trapped in a bizarre world surrounded by skyscrapers, where a masked man cracked open a man's head with an axe before her eyes. Finding a way to survive this bizarre world, find her beloved brother, and escape becomes her top priority, but she is beset by danger not just from the mysterious Masks, which possess both inhuman strength and cruelty, but other survivors turned cruel or desparate by the insanity of the high-rise world.",
            'popularity': 63.022,
            'rating_average': 8.5,
            'rating_count': 348,
            'first_air_date': '2021-02-25',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/cT0o6RFi36TkMFG1wWyTyGb2jrR.jpg',
            'poster_path': '/5uXaWe0LXTpBQVBBXL1ynae1DED.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/112163',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 116174,
            'title': "It's a Sin",
            'genres': None,
            'overview':
            'A chronicle of five friends during a decade in which everything changed, including the rise of AIDS.',
            'popularity': 27.236,
            'rating_average': 8.5,
            'rating_count': 33,
            'first_air_date': '2021-01-22',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/aveywEVwIppkrHRQavbB4ybnZPe.jpg',
            'poster_path': '/hkoQ9Ut0mmQC8BmlScrGD78PlXw.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/116174',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }, {
            'code': 80828,
            'title': 'The Nevers',
            'genres': None,
            'overview':
            'In the last years of Victoria\'s reign, London is beset by the "Touched": people — mostly women — who suddenly manifest abnormal abilities, some charming, some very disturbing. Among them are Amalia True, a mysterious, quick-fisted widow, and Penance Adair, a brilliant young inventor. They are the champions of this new underclass, making a home for the Touched, while fighting the forces of… well, pretty much all the forces — to make room for those whom history as we know it has no place.',
            'popularity': 65.552,
            'rating_average': 8.5,
            'rating_count': 321,
            'first_air_date': '2021-04-11',
            'last_air_date': None,
            'status': None,
            'backdrop_path': '/6x8vW5utEZahp6V3sSWxCTW0mHW.jpg',
            'poster_path': '/v6Xmj8Fy7ZruVTz3y2Po7O0TQh4.jpg',
            'providers': None,
            'cast': None,
            'creators': None,
            'number_of_episodes': None,
            'number_of_seasons': None,
            'tmdb_url': 'https://www.themoviedb.org/tv/80828',
            'watch_status': None,
            'rating_user': None,
            'favorite': None,
            'runtime': None,
            '__typename': 'TV'
        }]
    }

    assert dict == get_by_rating("e3b0c4429@e3b0c4429.com", tmdb, "TV", 5, 10,
                                 "2021-01-01", 1)
