"""Use non-overlapping attribute IDs.

Revision ID: 066863c10e01
Revises: 6676c18417dc
Create Date: 2021-05-11 16:04:11.796991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066863c10e01'
down_revision = '6676c18417dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cache', sa.Column('query_content', sa.Text(), nullable=False))
    op.add_column('cache', sa.Column('body_content', sa.Text(), nullable=True))
    op.drop_column('cache', 'body')
    op.drop_column('cache', 'query')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cache', sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('cache', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('cache', 'body_content')
    op.drop_column('cache', 'query_content')
    # ### end Alembic commands ###
