"""Add number_of_watched_seasons to media_data

Revision ID: 49cda4abb1bc
Revises: 97727d93cb1a
Create Date: 2021-05-19 10:25:59.049643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49cda4abb1bc'
down_revision = '97727d93cb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_data', sa.Column('number_of_watched_episodes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_data', 'number_of_watched_episodes')
    # ### end Alembic commands ###
