"""Add mynewtable.

Revision ID: 7d752933c03f
Revises: a4b6775b3c7e
Create Date: 2021-05-13 01:08:46.794033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d752933c03f'
down_revision = 'a4b6775b3c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('user_id_content', sa.Integer(), nullable=False),
    sa.Column('external_id_content', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id_content')
    )
    op.drop_table('user')
    op.drop_constraint('media_data_user_id_content_fkey', 'media_data', type_='foreignkey')
    op.create_foreign_key(None, 'media_data', 'user_data', ['user_id_content'], ['user_id_content'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_data', type_='foreignkey')
    op.create_foreign_key('media_data_user_id_content_fkey', 'media_data', 'user', ['user_id_content'], ['user_id_content'])
    op.create_table('user',
    sa.Column('user_id_content', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('external_id_content', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id_content', name='user_pkey')
    )
    op.drop_table('user_data')
    # ### end Alembic commands ###
