"""add tv code to media data

Revision ID: 80dca2594cae
Revises: 5501b68c1e47
Create Date: 2021-05-30 09:23:07.017484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80dca2594cae'
down_revision = '5501b68c1e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_data', sa.Column('tv_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_data', 'tv_code')
    # ### end Alembic commands ###
