"""Added created_on column to media_data

Revision ID: 895b695fca52
Revises: 80dca2594cae
Create Date: 2021-06-08 11:28:19.087787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895b695fca52'
down_revision = '80dca2594cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_data', sa.Column('created_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_data', 'created_on')
    # ### end Alembic commands ###
