"""Initial migration.

Revision ID: 8fba92a4c75e
Revises: 
Create Date: 2021-05-09 18:00:39.695712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fba92a4c75e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache',
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=True),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('query')
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_table('cache')
    # ### end Alembic commands ###
