"""Added i18n & country columns to user

Revision ID: af6ecd3bf5d6
Revises: 895b695fca52
Create Date: 2021-06-08 11:58:19.876250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6ecd3bf5d6'
down_revision = '895b695fca52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('language', sa.String(length=30), nullable=True))
    op.add_column('user_data', sa.Column('country', sa.String(length=30), nullable=True))
    op.execute("UPDATE user_data SET language = 'en-US'")
    op.execute("UPDATE user_data SET country = 'US'")
    op.alter_column('user_data', 'language', nullable=False)
    op.alter_column('user_data', 'country', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'country')
    op.drop_column('user_data', 'language')
    # ### end Alembic commands ###
