name: hydrun CI

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up hydrun
        run: |
          curl -L -o /tmp/hydrun "https://github.com/pojntfx/hydrun/releases/latest/download/hydrun.linux-$(uname -m)"
          sudo install /tmp/hydrun /usr/local/bin
      - name: Start database
        run: |
          docker volume create consumatio-postgres
          docker network create consumatio-backend-testing
          docker run --network consumatio-backend-testing --name consumatio-postgres -d -e POSTGRES_USER=consumatio-postgres -e POSTGRES_PASSWORD=consumatio-postgres -e POSTGRES_DB=consumatio-postgres -p 5432:5432 -v consumatio-postgres:/var/lib/postgresql/data postgres postgres -N 512
          sleep 5 # Wait for the DB to start
      - name: Test with hydrun
        run: hydrun --extra-args='--network consumatio-backend-testing -e DATABASE_URI=postgresql://consumatio-postgres:consumatio-postgres@consumatio-postgres:5432/consumatio-postgres' './Hydrunfile test'
      - name: Build backend binary with hydrun
        run: hydrun -a amd64,arm64 './Hydrunfile binary'
      - name: Fix permissions for built binary
        run: sudo chown -R $USER out
      - name: Publish pre-release to GitHub releases
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: unstable
          prerelease: true
          files: |
            out/release/*
      - name: Publish release to GitHub releases
        if: startsWith(github.ref, 'refs/tags/v')
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            out/release/*
